baseURL = 'https://example.org/'
title = 'AddRoll'
theme = 'ananke'
SectionPagesMenu = 'main'

languageCode = 'pt-pt'
defaultContentLanguage = 'pt'

[cascade]
featured_image = '/images/hero-wide.jpg'

[params]
read_more_copy = 'Detalhes'
featured_image_class = 'cover bg-bottom'

[pagination]
pagerSize = 6

[caches.images]
dir = ':cacheDir/images'

[outputFormats.ICS]
baseName = "boardgames-event"
path = "calendar"
mediaType = "text/calendar"
isPlainText = true
notAlternative = true
permalinkable = true

[outputs]
home = ["HTML", "ICS"]

