name: Pull Request CI

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

jobs:
  test-build:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/test-build.yaml

  check-fixups:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/check-fixups.yaml
